package Pharmacy;


import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.jar.Attributes.Name;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lenovo pc
 */
public class ajouter extends javax.swing.JFrame {

    /**
     * Creates new form ajouter
     */
    public ajouter() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        medicaN = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nLot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("La saisie des données");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(298, 30, 177, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Entrer un nouveau médicament");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(198, 70, 323, 52);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nom de médicaments :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 160, 185, 31);

        medicaN.setEditable(true);
        medicaN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        medicaN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        medicaN.setToolTipText("");
        medicaN.setInheritsPopupMenu(true);
        medicaN.setLightWeightPopupEnabled(false);
        medicaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicaNActionPerformed(evt);
            }
        });
        jPanel1.add(medicaN);
        medicaN.setBounds(230, 160, 203, 31);
        medicaN.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("N°Lot");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 160, 62, 36);

        nLot.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nLotActionPerformed(evt);
            }
        });
        jPanel1.add(nLot);
        nLot.setBounds(560, 160, 110, 36);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Date Exp :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 250, 89, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Stock courant");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 320, 133, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Quantité :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 370, 89, 31);

        quantity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity);
        quantity.setBounds(290, 370, 85, 31);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Prix :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 370, 64, 30);

        price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(560, 370, 80, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Enregestrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 440, 180, 43);

        day.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(day);
        day.setBounds(280, 250, 60, 30);

        month.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Jullie", "aout", "Séptembre", "Octobre", "Novembre", "Décembre" }));
        jPanel1.add(month);
        month.setBounds(350, 250, 110, 30);

        year.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year);
        year.setBounds(470, 250, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nLotActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed
    public String toString(Object obj) {
        return String.valueOf(obj);
    }
    public void setDefault() {
        medicaN.getEditor().setItem("");
        quantity.setText("");
        nLot.setText("");
        price.setText("");
        day.setSelectedIndex(0);
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);        
    }
    
    Connection conn = null;
    PreparedStatement preapared = null;
    ResultSet rs = null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        
        String MyItem = medicaN.getEditor().getItem().toString().trim();
        String Nlot = nLot.getText().trim();
        String day = toString(this.day.getSelectedItem()).trim();
        String month = toString(this.month.getSelectedItem()).trim();
        String year = toString(this.year.getSelectedItem()).trim();
        String quantity = this.quantity.getText().trim();
        String price = this.price.getText().trim();
//        String montant = String.valueOf(Integer.parseInt(quantity) * Integer.parseInt(price));
        
        String fullExpDate = year + "-" + month + "-" + day;
        conn = connection.getConnection();
        if (MyItem.equals("") || Nlot.equals("") || quantity.equals("") || price.equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Avertissement", 0);
        } else {
            try {
                String insert = "INSERT INTO `medicaments`(name , nlot, exday, exmonth, exyear,fullexp , quantity, rstocke, price) VALUES(? , ? , ? , ? , ? , ? , ? , ? , ? ) ";
                preapared = conn.prepareStatement(insert);
                preapared.setString(1, MyItem);
                preapared.setString(2, Nlot);
                preapared.setString(3, day);
                preapared.setString(4, month);
                preapared.setString(5, year);
                preapared.setString(6, fullExpDate);
                preapared.setString(7, quantity);
                preapared.setString(8, quantity);
                preapared.setString(9, price);
                if (preapared.executeUpdate() == 1) {
                    medicaN.addItem(String.valueOf(MyItem));
                    JOptionPane.showMessageDialog(null, "L'enregestrement ajouter avec succés");                                       
                    setDefault();
                } else {
                    JOptionPane.showMessageDialog(null, "Les informations n'ont pas pu etre saisies");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ce médicament est déjà sur la base de données");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void medicaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicaNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicaNActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
        //new index(jComboBox4.getText()).setVisible(true);
    }//GEN-LAST:event_yearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        connection.showMedicamentsInJCombo(medicaN);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        index Index = new index();
        Index.setLocationRelativeTo(null);
        Index.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> medicaN;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField nLot;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
